// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RespectCounter.Infrastructure;

#nullable disable

namespace RespectCounter.Infrastructure.Migrations
{
    [DbContext(typeof(RespectDbContext))]
    partial class RespectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b1f5bcf-ee2b-46c5-8d6e-662a61814493"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("0da47907-7151-4366-8fb9-181765bc6918"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e037e996-395a-4a07-9336-3d1e7ac2b934"),
                            RoleId = new Guid("4b1f5bcf-ee2b-46c5-8d6e-662a61814493")
                        },
                        new
                        {
                            UserId = new Guid("959b176f-bb8a-4694-94f1-ac6ad072d0a6"),
                            RoleId = new Guid("0da47907-7151-4366-8fb9-181765bc6918")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Happend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("PersonId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e57c257-def4-4532-9325-dc162c3bca46"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6478),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test description",
                            Happend = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6478),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Location = "",
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7"),
                            Source = "Dude, just trust me",
                            Status = "NotVerified",
                            Type = "Quote",
                            Value = "Milik jest słaby"
                        },
                        new
                        {
                            Id = new Guid("960765aa-244d-474b-b969-3f5d2338e777"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6566),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Można utknąć w eeeee korku",
                            Happend = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6566),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Location = "Monaco, MC",
                            PersonId = new Guid("bb683711-c610-4b50-8576-caee58437e52"),
                            Source = "https://www.youtube.com/watch?v=qbYMoKxif6I",
                            Status = "Verified",
                            Type = "Act",
                            Value = "Monaco GP 2010: Robeeeeeeeert Kubica P2 in Quali"
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityTag", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityId", "TagId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityTags");

                    b.HasData(
                        new
                        {
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46"),
                            TagId = new Guid("8654b0d9-7d49-4ced-8797-8100583f4772"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8350),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8351),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46"),
                            TagId = new Guid("d194bec8-ee58-49cf-87f2-96e070997dc9"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8356),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8356),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ActivityId = new Guid("960765aa-244d-474b-b969-3f5d2338e777"),
                            TagId = new Guid("8654b0d9-7d49-4ced-8797-8100583f4772"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8358),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8359),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ActivityId = new Guid("960765aa-244d-474b-b969-3f5d2338e777"),
                            TagId = new Guid("e55f0aab-3ef1-4b94-8700-0f929343c714"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8360),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8361),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.BaseReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllChildrenCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DirectChildrenCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ParentId");

                    b.HasIndex("PersonId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3791ec9d-3764-47e3-b08b-2fd97de93fe5"),
                            AllChildrenCount = 2,
                            Content = "Najlepszy zawodnik!",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6804),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 2,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6804),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("89924f9e-d6bd-45b9-adfa-719993b38ae1"),
                            AllChildrenCount = 0,
                            Content = "No nie wiem. Milik lepszy!",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6870),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6870),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("3791ec9d-3764-47e3-b08b-2fd97de93fe5"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6e4c16c8-70e4-4a31-9e90-65e99d6ca77c"),
                            AllChildrenCount = 0,
                            Content = "Jest całkiem dobry faktycznie",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6902),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6902),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("3791ec9d-3764-47e3-b08b-2fd97de93fe5"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4368bcac-c6a5-41f3-b1b7-56fbccac97af"),
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46"),
                            AllChildrenCount = 2,
                            Content = "Fajność!",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6928),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 2,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6928),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eeda22f0-99bc-4af6-b973-47071738c89e"),
                            AllChildrenCount = 0,
                            Content = "Zgadza się!",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6952),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6952),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("4368bcac-c6a5-41f3-b1b7-56fbccac97af"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0f278b96-aa7c-45f4-976e-3b0b12ee513b"),
                            AllChildrenCount = 0,
                            Content = "Też się zgadzam. Fajność!",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6974),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6974),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("4368bcac-c6a5-41f3-b1b7-56fbccac97af"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fe83f076-b60a-430c-9401-dee9422a31a3"),
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46"),
                            AllChildrenCount = 1,
                            Content = "Niefajność",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6982),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 1,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6982),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("898ee461-f014-4a85-b8c3-fd289b3e6dd0"),
                            AllChildrenCount = 0,
                            Content = "Nie zgadzam się. Fajność.",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6995),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6995),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("fe83f076-b60a-430c-9401-dee9422a31a3"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2e71ed28-e86a-40f3-8856-8833ee3fea46"),
                            ActivityId = new Guid("960765aa-244d-474b-b969-3f5d2338e777"),
                            AllChildrenCount = 0,
                            Content = "Lepsza weeeeeersja: https://www.youtube.com/watch?v=vmLonweq6wA",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7022),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7022),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("684e8514-4717-4677-9cb8-5394c931cb10"),
                            AllChildrenCount = 3,
                            Content = "Bardzo memiczna osoba",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7040),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 2,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7040),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("9ea590e1-0646-4255-a1f7-6b8b7f87a967"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5f453278-1214-45bf-ad1d-f62ef540bce0"),
                            AllChildrenCount = 0,
                            Content = "Hańba!",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7062),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7062),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("684e8514-4717-4677-9cb8-5394c931cb10"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("75d8cffa-3335-4911-8749-ff9872249fad"),
                            AllChildrenCount = 0,
                            Content = "Chyba ty",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7076),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7076),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("684e8514-4717-4677-9cb8-5394c931cb10"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("17acc2c9-a090-4810-bda6-061192569a30"),
                            AllChildrenCount = 0,
                            Content = "Nie, bo ty",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7088),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7088),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("75d8cffa-3335-4911-8749-ff9872249fad"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2d7291a0-f4fd-456c-9c16-0fed384f4ad2"),
                            AllChildrenCount = 0,
                            Content = "Ja tam mu nei ufam",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7103),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7103),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("9ea590e1-0646-4255-a1f7-6b8b7f87a967"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("142fb2fb-64ef-4ab8-a8fa-1e1d0d8b2630"),
                            AllChildrenCount = 0,
                            Content = "Nie lubiem go, bo Andrzej to dziwne imię",
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7112),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7112),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("9ea590e1-0646-4255-a1f7-6b8b7f87a967"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7"),
                            Birthday = new DateOnly(1988, 8, 21),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(5272),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Robert",
                            LastName = "Lewandowski",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(5272),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "Lewy",
                            Profession = "Footballer",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bb683711-c610-4b50-8576-caee58437e52"),
                            Birthday = new DateOnly(1984, 12, 7),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6055),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Robert",
                            LastName = "Kubica",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6055),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "",
                            Profession = "Racer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9ea590e1-0646-4255-a1f7-6b8b7f87a967"),
                            Birthday = new DateOnly(1972, 5, 16),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6102),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Andrzej",
                            LastName = "Duda",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6102),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "",
                            Profession = "Politician",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4b8055d3-427b-405b-9284-0ebdd70f7ec2"),
                            Birthday = new DateOnly(1957, 4, 22),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6129),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Donald",
                            LastName = "Tusk",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(6129),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "",
                            Profession = "Politician",
                            Status = 1
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonTag", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonId", "TagId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("TagId");

                    b.ToTable("PersonTag");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7"),
                            TagId = new Guid("8654b0d9-7d49-4ced-8797-8100583f4772"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8110),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8111),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("bb683711-c610-4b50-8576-caee58437e52"),
                            TagId = new Guid("8654b0d9-7d49-4ced-8797-8100583f4772"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8116),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8117),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7"),
                            TagId = new Guid("d194bec8-ee58-49cf-87f2-96e070997dc9"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8119),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8119),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7"),
                            TagId = new Guid("223f09a8-5690-4f78-ab80-c1f5ee4475cd"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8121),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8122),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("bb683711-c610-4b50-8576-caee58437e52"),
                            TagId = new Guid("e55f0aab-3ef1-4b94-8700-0f929343c714"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8124),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8124),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("bb683711-c610-4b50-8576-caee58437e52"),
                            TagId = new Guid("1cedff05-fea4-43a0-9ac1-937a0342ab47"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8127),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8128),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("9ea590e1-0646-4255-a1f7-6b8b7f87a967"),
                            TagId = new Guid("0a1423bd-c6ee-42f3-90fc-9148e90a795a"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8132),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8132),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("4b8055d3-427b-405b-9284-0ebdd70f7ec2"),
                            TagId = new Guid("0a1423bd-c6ee-42f3-90fc-9148e90a795a"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8134),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8135),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("9ea590e1-0646-4255-a1f7-6b8b7f87a967"),
                            TagId = new Guid("913bd01f-3572-4d63-be37-6d18c2879f97"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8137),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8137),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PersonId = new Guid("4b8055d3-427b-405b-9284-0ebdd70f7ec2"),
                            TagId = new Guid("d8f613fc-2d90-469b-a378-cac1cbc667a7"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8139),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000000"),
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8140),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8654b0d9-7d49-4ced-8797-8100583f4772"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7432),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7432),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("d194bec8-ee58-49cf-87f2-96e070997dc9"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7479),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7479),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Football"
                        },
                        new
                        {
                            Id = new Guid("223f09a8-5690-4f78-ab80-c1f5ee4475cd"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7497),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7497),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = new Guid("e55f0aab-3ef1-4b94-8700-0f929343c714"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7635),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7635),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "F1"
                        },
                        new
                        {
                            Id = new Guid("1cedff05-fea4-43a0-9ac1-937a0342ab47"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7661),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7661),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "WEC"
                        },
                        new
                        {
                            Id = new Guid("0a1423bd-c6ee-42f3-90fc-9148e90a795a"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7684),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7684),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Politics"
                        },
                        new
                        {
                            Id = new Guid("913bd01f-3572-4d63-be37-6d18c2879f97"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7701),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7701),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "PiS"
                        },
                        new
                        {
                            Id = new Guid("d8f613fc-2d90-469b-a378-cac1cbc667a7"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7710),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(7710),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "PO"
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("DomainUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 614, DateTimeKind.Utc).AddTicks(7350),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 614, DateTimeKind.Utc).AddTicks(7350),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "System"
                        },
                        new
                        {
                            Id = new Guid("e037e996-395a-4a07-9336-3d1e7ac2b934"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 614, DateTimeKind.Utc).AddTicks(7350),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 614, DateTimeKind.Utc).AddTicks(7350),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("959b176f-bb8a-4694-94f1-ac6ad072d0a6"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 614, DateTimeKind.Utc).AddTicks(7350),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 614, DateTimeKind.Utc).AddTicks(7350),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("RespectCounter.Infrastructure.Identity.CustomIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9bdbfe87-8e21-4bf5-a512-3cfb9f163332",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SYSTEM_USER",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "system_user"
                        },
                        new
                        {
                            Id = new Guid("e037e996-395a-4a07-9336-3d1e7ac2b934"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f30297b7-6f4f-48d6-bfb6-c80ce59c4ae3",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEAO/iYzc255MLkEF24ZhmOHOF1XwVaNi0bb7XeXVgndlHknUDF+Nb3fdOt7i/i70DA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b35ece43-c49b-4b43-a951-8e0c2af18931",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("959b176f-bb8a-4694-94f1-ac6ad072d0a6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59367c57-3cab-47df-adcb-c9a72bfd1dfa",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAECh69bYd/Uk/dwOL567jKt9SWxzUFpJ3hDdZ9axGLxJTqSp2BCMa2ZQqzqOXAjG0XA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b57cd635-f6f6-4b59-98b5-699c1a14af52",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.Property<Guid>("RecentlyBrowsedTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecentlyBrowsedTagsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRecentlyBrowsedTags", (string)null);
                });

            modelBuilder.Entity("TagUser1", b =>
                {
                    b.Property<Guid>("FavoriteTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoriteTagsId", "User1Id");

                    b.HasIndex("User1Id");

                    b.ToTable("UserFavoriteTags", (string)null);
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityReaction", b =>
                {
                    b.HasBaseType("RespectCounter.Domain.Model.BaseReaction");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityReactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("93576565-0c14-4a0d-8f38-9f196f93d50a"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8715),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8715),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46")
                        },
                        new
                        {
                            Id = new Guid("7985c37a-a59f-425a-8cb3-5b759a727253"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8740),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8740),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = -1,
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46")
                        },
                        new
                        {
                            Id = new Guid("88b45527-efe7-4942-b56f-1466b825a4ef"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8756),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8756),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46")
                        },
                        new
                        {
                            Id = new Guid("0baee526-2c86-4ec5-b7ff-b1085269325d"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8766),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8766),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            ActivityId = new Guid("5e57c257-def4-4532-9325-dc162c3bca46")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.CommentReaction", b =>
                {
                    b.HasBaseType("RespectCounter.Domain.Model.BaseReaction");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentReactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("57fd04d4-5ab3-43a3-a0dd-29e290d47c41"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8986),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8986),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            CommentId = new Guid("3791ec9d-3764-47e3-b08b-2fd97de93fe5")
                        },
                        new
                        {
                            Id = new Guid("0b24e92f-da5f-457e-81eb-ff41ee877f35"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(9013),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(9013),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            CommentId = new Guid("4368bcac-c6a5-41f3-b1b7-56fbccac97af")
                        },
                        new
                        {
                            Id = new Guid("dea0704b-3b6f-4ea7-bb93-e7f6f99b6aa3"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(9031),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(9031),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            CommentId = new Guid("4368bcac-c6a5-41f3-b1b7-56fbccac97af")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonReaction", b =>
                {
                    b.HasBaseType("RespectCounter.Domain.Model.BaseReaction");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonReactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3edaddee-3531-49ec-8bfd-f3a68c35e667"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8481),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8481),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = -2,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("b65b0951-601a-42ec-8b01-ecb2cfbbdd27"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8514),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8514),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("0f4929d8-2160-4934-aeed-ae5aa5b90bdc"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8529),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8529),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = -1,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("f93044ae-fe11-4929-8e50-69f710ab2775"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8536),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8536),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("4765dba1-879a-4bfb-8fe1-d17023c74f6e"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8543),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8543),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("72be4ae8-726c-40a4-8b71-9ede53a89daf"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8553),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8553),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("b250bb3e-d705-4983-98d8-545530f131d9"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8565),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8565),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        },
                        new
                        {
                            Id = new Guid("1ef89e76-56c9-4c91-aaca-e457866bed85"),
                            Created = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8572),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 10, 30, 21, 11, 47, 889, DateTimeKind.Utc).AddTicks(8572),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("ad612e08-7e7b-4b51-a876-2cc78280cfe7")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Activity", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Activities")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityTag", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Activity", "Activity")
                        .WithMany("Tags")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Tag", "Tag")
                        .WithMany("Activities")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.BaseReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Comment", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Activity", "Activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Comment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Comments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Parent");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Person", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonTag", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Tags")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Tag", "Tag")
                        .WithMany("Persons")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Person");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Tag", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.User", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithOne("Profile")
                        .HasForeignKey("RespectCounter.Domain.Model.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("RecentlyBrowsedTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagUser1", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("FavoriteTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Activity", "Activity")
                        .WithMany("Reactions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.CommentReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Reactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Activity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Comment", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Person", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Tag", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("RespectCounter.Infrastructure.Identity.CustomIdentityUser", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
