// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RespectCounter.Infrastructure;

#nullable disable

namespace RespectCounter.Infrastructure.Migrations
{
    [DbContext(typeof(RespectDbContext))]
    partial class RespectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c5e637-9d76-447f-a45e-9330d048b861"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c60d7ecd-2ead-4094-a536-83567e36052f"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("324f50c4-b332-4199-9f10-5406a11119da"),
                            RoleId = new Guid("b2c5e637-9d76-447f-a45e-9330d048b861")
                        },
                        new
                        {
                            UserId = new Guid("59c900f0-d4e2-4e41-9811-5e929e476192"),
                            RoleId = new Guid("c60d7ecd-2ead-4094-a536-83567e36052f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Happend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("PersonId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4599),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test description",
                            Happend = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4599),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Location = "",
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096"),
                            Source = "Dude, just trust me",
                            Status = "NotVerified",
                            Type = "Quote",
                            Value = "Milik jest słaby"
                        },
                        new
                        {
                            Id = new Guid("ae1e8651-e6a5-487b-823f-6f6f60c4cc6e"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4658),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Można utknąć w eeeee korku",
                            Happend = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4658),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Location = "Monaco, MC",
                            PersonId = new Guid("93eec7b8-5c84-424d-a455-f66a1ba72cca"),
                            Source = "https://www.youtube.com/watch?v=qbYMoKxif6I",
                            Status = "Verified",
                            Type = "Act",
                            Value = "Monaco GP 2010: Robeeeeeeeert Kubica P2 in Quali"
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityTag", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityId", "TagId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityTags");

                    b.HasData(
                        new
                        {
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b"),
                            TagId = new Guid("16821f42-1144-4cf6-9f0e-77856aafad6c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b"),
                            TagId = new Guid("01cf2487-4d3f-453c-bc71-29d8d645771e"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ActivityId = new Guid("ae1e8651-e6a5-487b-823f-6f6f60c4cc6e"),
                            TagId = new Guid("16821f42-1144-4cf6-9f0e-77856aafad6c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ActivityId = new Guid("ae1e8651-e6a5-487b-823f-6f6f60c4cc6e"),
                            TagId = new Guid("321c6ccd-a45f-4472-adee-59917aa7c727"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.BaseReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllChildrenCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DirectChildrenCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ParentId");

                    b.HasIndex("PersonId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("adec7066-9bb6-44c7-9563-bfd50d8d1700"),
                            AllChildrenCount = 2,
                            Content = "Najlepszy zawodnik!",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4773),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 2,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4773),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bc002a4b-c5cc-4e91-be84-6b09478c2a11"),
                            AllChildrenCount = 0,
                            Content = "No nie wiem. Milik lepszy!",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4813),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4813),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("adec7066-9bb6-44c7-9563-bfd50d8d1700"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("31bcfe1e-c564-4281-b0a4-2db1eda235bb"),
                            AllChildrenCount = 0,
                            Content = "Jest całkiem dobry faktycznie",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4820),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4820),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("adec7066-9bb6-44c7-9563-bfd50d8d1700"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("46e439f2-aca0-4c06-ba78-9667bf7ab9eb"),
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b"),
                            AllChildrenCount = 2,
                            Content = "Fajność!",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4832),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 2,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4832),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3ed95dee-06e1-4fbe-a83a-1c80cdeaceae"),
                            AllChildrenCount = 0,
                            Content = "Zgadza się!",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4839),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4839),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("46e439f2-aca0-4c06-ba78-9667bf7ab9eb"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e2428ee9-4830-4a6e-9f75-1b72091d010f"),
                            AllChildrenCount = 0,
                            Content = "Też się zgadzam. Fajność!",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4847),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4847),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("46e439f2-aca0-4c06-ba78-9667bf7ab9eb"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("088fb9dc-93d8-4895-9c9d-a86efd404598"),
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b"),
                            AllChildrenCount = 1,
                            Content = "Niefajność",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4853),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 1,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4853),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("abd73285-480d-49ac-adf4-9ec9cc8c6f51"),
                            AllChildrenCount = 0,
                            Content = "Nie zgadzam się. Fajność.",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4860),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4860),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("088fb9dc-93d8-4895-9c9d-a86efd404598"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d3d8ada6-a342-4763-9ff5-38eb3e19b374"),
                            ActivityId = new Guid("ae1e8651-e6a5-487b-823f-6f6f60c4cc6e"),
                            AllChildrenCount = 0,
                            Content = "Lepsza weeeeeersja: https://www.youtube.com/watch?v=vmLonweq6wA",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4872),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4872),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5bb0cb86-8a1d-42a8-8dbe-eb1873fd1cb8"),
                            AllChildrenCount = 3,
                            Content = "Bardzo memiczna osoba",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4877),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 2,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4877),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("85323f6e-bcd2-41e2-9e10-4a352c2f141f"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("28fdf3e9-c247-4c27-97c8-e0248e78d6f5"),
                            AllChildrenCount = 0,
                            Content = "Hańba!",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4885),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4885),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("5bb0cb86-8a1d-42a8-8dbe-eb1873fd1cb8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("56756984-fcee-4a8c-af76-13c64fabf98e"),
                            AllChildrenCount = 0,
                            Content = "Chyba ty",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4891),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4891),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("5bb0cb86-8a1d-42a8-8dbe-eb1873fd1cb8"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8c256ed6-b5c8-406e-afcd-99628bb10e8a"),
                            AllChildrenCount = 0,
                            Content = "Nie, bo ty",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4898),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4898),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ParentId = new Guid("56756984-fcee-4a8c-af76-13c64fabf98e"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eeea95f9-04ab-49ef-9928-ac74035c90c9"),
                            AllChildrenCount = 0,
                            Content = "Ja tam mu nei ufam",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4909),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4909),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("85323f6e-bcd2-41e2-9e10-4a352c2f141f"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2fc60632-d57c-4380-ad25-184fa4a6c5fc"),
                            AllChildrenCount = 0,
                            Content = "Nie lubiem go, bo Andrzej to dziwne imię",
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4916),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            DirectChildrenCount = 0,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4916),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            PersonId = new Guid("85323f6e-bcd2-41e2-9e10-4a352c2f141f"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19888f5c-f999-4673-ab6d-f0a487194096"),
                            Birthday = new DateOnly(1988, 8, 21),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4204),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Robert",
                            LastName = "Lewandowski",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4204),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "Lewy",
                            Profession = "Footballer",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("93eec7b8-5c84-424d-a455-f66a1ba72cca"),
                            Birthday = new DateOnly(1984, 12, 7),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4296),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Robert",
                            LastName = "Kubica",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4296),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "",
                            Profession = "Racer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("85323f6e-bcd2-41e2-9e10-4a352c2f141f"),
                            Birthday = new DateOnly(1972, 5, 16),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4317),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Andrzej",
                            LastName = "Duda",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4317),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "",
                            Profession = "Politician",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("dd06393a-7555-44e7-b9f2-bb3089f36eb0"),
                            Birthday = new DateOnly(1957, 4, 22),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4327),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            DeathDate = new DateOnly(1, 1, 1),
                            Deleted = false,
                            Description = "Test desc",
                            FirstName = "Donald",
                            LastName = "Tusk",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(4327),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Nationality = "Polish",
                            NickName = "",
                            Profession = "Politician",
                            Status = 1
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonTag", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonId", "TagId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("TagId");

                    b.ToTable("PersonTag");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096"),
                            TagId = new Guid("16821f42-1144-4cf6-9f0e-77856aafad6c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("93eec7b8-5c84-424d-a455-f66a1ba72cca"),
                            TagId = new Guid("16821f42-1144-4cf6-9f0e-77856aafad6c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096"),
                            TagId = new Guid("01cf2487-4d3f-453c-bc71-29d8d645771e"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096"),
                            TagId = new Guid("7ce7c993-8a63-4484-97bf-98f2aa1ed8f7"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("93eec7b8-5c84-424d-a455-f66a1ba72cca"),
                            TagId = new Guid("321c6ccd-a45f-4472-adee-59917aa7c727"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("93eec7b8-5c84-424d-a455-f66a1ba72cca"),
                            TagId = new Guid("5d61e0a7-6eba-4163-91ce-31748678493c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("93eec7b8-5c84-424d-a455-f66a1ba72cca"),
                            TagId = new Guid("8c74fb36-121e-4e1f-b9ab-0cb151110a84"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("dd06393a-7555-44e7-b9f2-bb3089f36eb0"),
                            TagId = new Guid("8c74fb36-121e-4e1f-b9ab-0cb151110a84"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("85323f6e-bcd2-41e2-9e10-4a352c2f141f"),
                            TagId = new Guid("7361172f-79d0-449f-891a-3d378ea43e5a"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PersonId = new Guid("dd06393a-7555-44e7-b9f2-bb3089f36eb0"),
                            TagId = new Guid("469acbde-8d55-4f6b-a278-001ca4e4acce"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7315),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16821f42-1144-4cf6-9f0e-77856aafad6c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5241),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5241),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("01cf2487-4d3f-453c-bc71-29d8d645771e"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5262),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5262),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Football"
                        },
                        new
                        {
                            Id = new Guid("7ce7c993-8a63-4484-97bf-98f2aa1ed8f7"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5267),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5267),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = new Guid("321c6ccd-a45f-4472-adee-59917aa7c727"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5272),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5272),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "F1"
                        },
                        new
                        {
                            Id = new Guid("5d61e0a7-6eba-4163-91ce-31748678493c"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5281),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5281),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "WEC"
                        },
                        new
                        {
                            Id = new Guid("8c74fb36-121e-4e1f-b9ab-0cb151110a84"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5289),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5289),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Politics"
                        },
                        new
                        {
                            Id = new Guid("7361172f-79d0-449f-891a-3d378ea43e5a"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5293),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5293),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "PiS"
                        },
                        new
                        {
                            Id = new Guid("469acbde-8d55-4f6b-a278-001ca4e4acce"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5298),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            Description = "Test desc",
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5298),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "PO"
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastUpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("DomainUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7919),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7919),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "System"
                        },
                        new
                        {
                            Id = new Guid("324f50c4-b332-4199-9f10-5406a11119da"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7919),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7919),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("59c900f0-d4e2-4e41-9811-5e929e476192"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7919),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 16, DateTimeKind.Utc).AddTicks(7919),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("RespectCounter.Infrastructure.Identity.CustomIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ed98c9c-fe85-4e45-8299-84d80f43eeea",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SYSTEM_USER",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "system_user"
                        },
                        new
                        {
                            Id = new Guid("324f50c4-b332-4199-9f10-5406a11119da"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33f1208a-ccf4-4f4a-aad9-36eedeaef95f",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELqnVWjFf2QyDXfRahRgzd2m1r2ykHNEItaDou+YhAtEIhnJpG94snQJX9ld4jSykQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4332a146-3e43-4c05-aafa-4a5f8b106ddc",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("59c900f0-d4e2-4e41-9811-5e929e476192"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37c5ae4b-b8a2-41be-bb38-a1014387a838",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAELZZbNb/nsTMZZDru/rRltH2ZUAw6ykmzy2ohOamRr8//+8tcWezGhHc4rkOhUakXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "99b0ce45-b1ff-4df6-8b79-823547c5c00f",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.Property<Guid>("RecentlyBrowsedTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecentlyBrowsedTagsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRecentlyBrowsedTags", (string)null);
                });

            modelBuilder.Entity("TagUser1", b =>
                {
                    b.Property<Guid>("FavoriteTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoriteTagsId", "User1Id");

                    b.HasIndex("User1Id");

                    b.ToTable("UserFavoriteTags", (string)null);
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityReaction", b =>
                {
                    b.HasBaseType("RespectCounter.Domain.Model.BaseReaction");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityReactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("79055356-99cd-4832-ab36-221548883a9d"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5891),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5891),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b")
                        },
                        new
                        {
                            Id = new Guid("3cb5be11-8574-453b-bc61-e408bfdea3a7"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5906),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5906),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = -1,
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b")
                        },
                        new
                        {
                            Id = new Guid("b6ba349d-d686-45e3-aefa-328a8ea8eddd"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5918),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5918),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b")
                        },
                        new
                        {
                            Id = new Guid("37f581f7-ce33-41f1-9897-d70ee6d8a718"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5924),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5924),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            ActivityId = new Guid("8102a794-9d84-4c94-95d0-a2fe6545013b")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.CommentReaction", b =>
                {
                    b.HasBaseType("RespectCounter.Domain.Model.BaseReaction");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentReactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("56c0f115-285f-41ff-b545-58b95bd801b4"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(6029),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(6029),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            CommentId = new Guid("adec7066-9bb6-44c7-9563-bfd50d8d1700")
                        },
                        new
                        {
                            Id = new Guid("97de4189-134a-4db1-a4a0-fda6bea3f5b7"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(6143),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(6143),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            CommentId = new Guid("46e439f2-aca0-4c06-ba78-9667bf7ab9eb")
                        },
                        new
                        {
                            Id = new Guid("343a47ac-90d1-4b0c-aa5d-6c4852e834fb"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(6155),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(6155),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            CommentId = new Guid("46e439f2-aca0-4c06-ba78-9667bf7ab9eb")
                        });
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonReaction", b =>
                {
                    b.HasBaseType("RespectCounter.Domain.Model.BaseReaction");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonReactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26af26ba-9d0f-4f25-af2d-900bd3bf23cc"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5729),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5729),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = -2,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("7c39ff90-c276-4d23-bdf3-233e2a89ab02"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5746),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5746),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("0f06fbb3-56de-42ee-8310-3603e96ae887"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5758),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5758),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = -1,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("82e641c3-b8f3-4aa5-8407-bc4933739f71"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5763),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5763),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 1,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("a8d47161-be64-4ccb-a105-d84f57b1ba1d"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5769),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5769),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("a82e3f2a-e96a-4388-9ab4-3a09d9a4d076"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5783),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5783),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("d2bab206-8167-4bf0-94dd-475c00dcea61"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5795),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5795),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        },
                        new
                        {
                            Id = new Guid("009edbd2-d688-4453-8b7c-ebb70fd1a6e7"),
                            Created = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5800),
                            CreatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            Deleted = false,
                            LastUpdated = new DateTime(2025, 11, 3, 16, 5, 53, 341, DateTimeKind.Utc).AddTicks(5800),
                            LastUpdatedById = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReactionType = 2,
                            PersonId = new Guid("19888f5c-f999-4673-ab6d-f0a487194096")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Activity", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Activities")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityTag", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Activity", "Activity")
                        .WithMany("Tags")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Tag", "Tag")
                        .WithMany("Activities")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.BaseReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Comment", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Activity", "Activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Comment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Comments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Parent");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Person", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonTag", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Tags")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.Tag", "Tag")
                        .WithMany("Persons")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("Person");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Tag", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.User", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RespectCounter.Infrastructure.Identity.CustomIdentityUser", null)
                        .WithOne("Profile")
                        .HasForeignKey("RespectCounter.Domain.Model.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("TagUser", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("RecentlyBrowsedTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagUser1", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("FavoriteTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RespectCounter.Domain.Model.User", null)
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.ActivityReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Activity", "Activity")
                        .WithMany("Reactions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.CommentReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.PersonReaction", b =>
                {
                    b.HasOne("RespectCounter.Domain.Model.Person", "Person")
                        .WithMany("Reactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Activity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Comment", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Person", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RespectCounter.Domain.Model.Tag", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("RespectCounter.Infrastructure.Identity.CustomIdentityUser", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
